# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx1G
org.gradle.parallel = true

# Gradle Plugins
loom_version = 1.15-SNAPSHOT
moddev_version = 2.0.141
versioning_version = 1.0.0
kpublish_version = 1.0.0
submodule_version = 0.11.1-beta.0.matti

# Fabric Properties
# check these on https://fabricmc.net/develop
java_version = 25
minecraft_version = 26.1
fabric_loader_version = 0.18.4
neoforge_version = 26.1.0.5-beta

# Mod Properties
project_version = 2.0.99+26.1.local
maven_group = com.kneelawk.codextra
archives_base_name = codextra
javadoc_package_name = com/kneelawk/codextra

# Dependencies
fapi_version = 0.144.3+26.1

# Javadoc Dependencies
jetbrains_annotations_version = 24.0.0
